name: pr-hello-world-command
on:
  issue_comment:
    types: [created, edited]

jobs:
  hello-world:
    if: >-
      github.event.issue.pull_request
      && startsWith(github.event.comment.body, '/hello-world')
    runs-on: ubuntu-latest

    steps:
      - name: Get PR HEAD ref
        id: pr-head-ref
        run: echo "pr_head_ref=$(gh pr view ${{ github.event.issue.number }} --repo ${{ github.repository }} --json headRefName | jq -r '.headRefName')" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr-head-ref.outputs.pr_head_ref }}

      - name: Append hello world
        run: echo "Hello, @${{ github.event.sender.login }}" >> files/hello-world.txt

      - name: Commit changes
        run: |
          git config --global user.name "actions-bot"
          git config --global user.email "58130806+actions-bot@users.noreply.github.com"
          git add -A
          git commit -m "[pr-hello-world-command] Hello response added!"
          git push
